# Generated by Django 5.0 on 2023-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('S', 'Élève'), ('T', 'Enseignant'), ('A', 'Administratif')], max_length=1),
        ),
    ]
