# Generated by Django 4.2.6 on 2023-12-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0018_course_teacher'),
        ('accounts', '0004_alter_user_class_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='scolaris_app.class'),
        ),
    ]
