# Generated by Django 5.0 on 2023-12-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0003_remove_course_code_remove_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField()),
                ('off', models.SmallIntegerField(default=20)),
            ],
        ),
    ]
