# Generated by Django 5.0 on 2023-12-19 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0007_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.class'),
        ),
    ]
