# Generated by Django 5.0 on 2023-12-19 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0009_mark_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='title',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('class_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.class')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.assessment'),
        ),
    ]
