# Generated by Django 5.0 on 2023-12-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0010_remove_mark_title_assessment_mark_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.subject'),
        ),
    ]
