# Generated by Django 5.0 on 2023-12-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0013_assessment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('due_date', models.DateTimeField(null=True)),
                ('class_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.class')),
                ('due_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.course')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.subject')),
            ],
        ),
    ]
