# Generated by Django 5.0 on 2023-12-19 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0014_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='marked_as_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_course',
            field=models.ForeignKey(help_text="Le cours avant lequel le devoir doit être effectué, ne peut être qu'un cours de la classe dont c'est le devoir", null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.course'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
