# Generated by Django 5.0 on 2023-12-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0016_remove_homework_marked_as_done_homeworkcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
