# Generated by Django 4.2.6 on 2023-12-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0018_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subjects_taken',
            field=models.ManyToManyField(to='scolaris_app.subject'),
        ),
    ]
