# Generated by Django 4.2.6 on 2023-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0019_class_subjects_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
