# Generated by Django 4.2.6 on 2023-12-20 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scolaris_app', '0020_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'T'}, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
