# Generated by Django 5.0 on 2023-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0022_remove_mark_off_assessment_off_alter_mark_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='min',
            field=models.SmallIntegerField(default=0),
        ),
    ]
