# Generated by Django 5.0 on 2023-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0023_assessment_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.SmallIntegerField(null=True),
        ),
    ]
