# Generated by Django 5.0 on 2023-12-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0025_alter_mark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
