# Generated by Django 4.2.7 on 2024-03-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0026_alter_mark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_course',
            field=models.ForeignKey(blank=True, help_text="Le cours avant lequel le devoir doit être effectué, ne peut être qu'un cours de la classe dont c'est le devoir", null=True, on_delete=django.db.models.deletion.CASCADE, to='scolaris_app.course'),
        ),
    ]
