# Generated by Django 4.2.7 on 2024-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0027_alter_homework_due_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.CharField(max_length=50)),
                ('main', models.CharField(max_length=50)),
                ('dessert', models.CharField(max_length=50)),
                ('date', models.DateTimeField(unique=True)),
            ],
        ),
    ]
