# Generated by Django 4.2.7 on 2024-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolaris_app', '0028_canteenmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenmenu',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
